# Generated by Django 4.2.7 on 2023-12-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_date_written_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
